// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADp0L-cUkhnF2wFSthgvbRH3M3jnGND8U',
    appId: '1:152780753508:web:9ca5d52dda6c2ef30d6d71',
    messagingSenderId: '152780753508',
    projectId: 'agrifund-761fa',
    authDomain: 'agrifund-761fa.firebaseapp.com',
    storageBucket: 'agrifund-761fa.appspot.com',
    measurementId: 'G-V3B0GJH9MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTfiYMSk0NHYxF2qdm1Zp-Cyf7iruE8c',
    appId: '1:152780753508:android:d1a2deb79a7241ae0d6d71',
    messagingSenderId: '152780753508',
    projectId: 'agrifund-761fa',
    storageBucket: 'agrifund-761fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuswQkLzev2y0Arrs83iH7sX4jQDL8wYg',
    appId: '1:152780753508:ios:44a6fcc368db7a130d6d71',
    messagingSenderId: '152780753508',
    projectId: 'agrifund-761fa',
    storageBucket: 'agrifund-761fa.appspot.com',
    androidClientId: '152780753508-kbmeq3c2k8go3b9qci0matd2beb3opo0.apps.googleusercontent.com',
    iosClientId: '152780753508-586v5kr51c0ubgm7po035u90pcb6fgop.apps.googleusercontent.com',
    iosBundleId: 'com.cofarmer.cofarmer',
  );
}
